### ISSUE TITLE
Author's Issue: Please delete this repository.

### ISSUE THREAD

**Issue by Stereoarts** [BlazeWYSB/SSS_LUT_Tool#1]
I don't permit to upload my works(codes, images, models, motions, and documents) to public space. Please delete this repository.

So you must check model / motion's licenses. Almost models and motions aren't permitted using without MMD and redistribution.

**Comment by BlazeWYSB** [comment]
I made this by myself. You can check the shader it on https://zhuanlan.zhihu.com/p/496190234.
Model is exported from games with ninja as no skeleton model. It is not a MMD model.
Maybe you are talking about the poi shader, but I haven't used it on avatar. Forget to delect it, that's my fault, I will delect this part.

But you are not talking about this, I need your apology.

**Comment by BlazeWYSB** [comment]
> I don't permit to upload my works(codes, images, models, motions, and documents) to public space. Please delete this repository.
> 
> So you must check model / motion's licenses. Almost models and motions aren't permitted using without MMD and redistribution.

**Comment by BlazeWYSB** [comment]
> I don't permit to upload my works(codes, images, models, motions, and documents) to public space. Please delete this repository.
> 
> So you must check model / motion's licenses. Almost models and motions aren't permitted using without MMD and redistribution.

I made this by myself. You can check the shader it on https://zhuanlan.zhihu.com/p/496190234.
Model is exported from games with ninja as no skeleton model. It is not a MMD model.
Maybe you are talking about the poi shader, but I haven't used it on avatar. Forget to delect it, that's my fault, I will delect this part.

But you are not talking about this, I need your apology.

**Comment by BlazeWYSB** [comment]
> I don't permit to upload my works(codes, images, models, motions, and documents) to public space. Please delete this repository.
> 
> So you must check model / motion's licenses. Almost models and motions aren't permitted using without MMD and redistribution.

THIS REPOSITORT IS NOT YOUR WORK! YOU CAN NOT ASK ME TO DELETE THE WHOLE REPOSITORY!

However, I do miss to delect all the unuse 3rd part plugin before releasing, including your MMD4M Plugin. This is my fault, and I will delect this parts soon. 

But it is totally different from your words:
I made this by myself. You can check the shader it on https://zhuanlan.zhihu.com/p/496190234.
Model is exported from games with ninja as a no skeleton model, and rig with blender.
It is even not a MMD model, and do not rely on MMD4M Plugin.

I can understand your anger, and will delect your part. But your words would make confusion as if I have had copied others work, so I had to delect the whole repo, which is totally wrong!

As I think, even if I used your Plugin, your had better to ask me to change another model, because the main theme of this repo is not the model, it is the skin shader instead! Let alone the fact that the model is not a MMD model, and has nothing to do with MMD4M Plugin.

I am very troubled by your rude request. I think both of us need to check more carefully next time.

**Comment by Stereoarts** [comment]
Sorry for my mis pointing out, as you said this model is definitely your work. It's okay to delete my works from the commit history, not required to delete the whole repository.

**Comment by Stereoarts** [comment]
However I'm very tired. I'm facing the same issue on other repositories. I should shrink my activity.
